# Generated by Django 3.1.2 on 2020-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('model_name', models.CharField(choices=[('Naive', 'NAIVE'), ('SVM', 'SVM')], default='Naive', max_length=6)),
                ('field_name', models.TextField(default='This is a default value')),
            ],
        ),
    ]
