# Generated by Django 3.1.2 on 2020-11-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_prj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_2_accuracy',
            field=models.CharField(default='top2', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='top_3_accuracy',
            field=models.CharField(default='top3', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='top_4_accuracy',
            field=models.CharField(default='top4', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='model_name',
            field=models.CharField(choices=[('Naive', 'NAIVE'), ('SVM', 'SVM'), ('Grid', 'GRID')], default='Naive', max_length=6),
        ),
    ]
