# Generated by Django 3.1.2 on 2020-11-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_prj', '0003_auto_20201115_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_1_percentage',
            field=models.CharField(default='per1', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='top_2_percentage',
            field=models.CharField(default='per2', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='top_3_percentage',
            field=models.CharField(default='per3', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='top_4_percentage',
            field=models.CharField(default='per4', max_length=100),
        ),
    ]
