# Generated by Django 3.1.3 on 2020-11-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_prj', '0004_auto_20201115_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='model_name',
            field=models.CharField(choices=[('Naive', 'NAIVE'), ('SVM', 'SVM'), ('Grid', 'GRID'), ('Tree', 'TREE'), ('Linear', 'LINEAR'), ('Kneast', 'KNEARST'), ('DL1', 'Deeplearning_Duc'), ('DL2', 'Deeplearning_Lam'), ('More_1', 'MORE_1'), ('More_2', 'MORE_2')], default='Naive', max_length=6),
        ),
    ]
